general:
  template_path: "./views/"
  readme_path: "./readme/"
  server_port: 8000
  max_concurrency: 2
site:
  site_name: "INDEX DEV"
  site_url: "http://localhost:8000"
  theme_link: "http://localhost:9000"
cookie:
  mac_secret: "secret string which has over 256-bit entropy"
  secure: false
database:
  database_type: "sqlite3"
  database_path: "./pc-index.db"
supplement:
  database_path: "./pc-suppl.bt"
csrf:
  key: "csrf_token"
  coockie: "XSRF-TOKEN"
  header: "X-XSRF-TOKEN"
github:
  client_id: "c74abcf03e61e209b3c3"
  client_secret: "da0f7d33d02552282e72a7e594d39ba76f96d478"
vpn:
  conn_check: false
  vpn_host: "198.199.115.209"
update:
  force_readme: false
  max_release_collect: 30
  max_release_rebuild: 15
  meta_update_record: "./meta-updated.log"
  meta_update_interval: 10
  supp_update_record: "./supp-updated.log"
  supp_update_interval: 15
